prose:
  rooturl: '_posts'
  siteurl: 'http://conference2013.diversitywoman.com'
  media: 'assets/images/uploads'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts/honorees:
      - name: "layout"
          element: "hidden"
          value: "speaker"
      - name: 'date'
          element: 'hidden'
      - name: 'honor'
          element: 'select'
          label: 'Select a Honoree Category'
          help: 'Select a category'

name: Diversity Woman
pygments: false
markdown: kramdown
paginate: 10
version: 0.9
seo:
  author: "Nicholas Kingston, Scott Schaffter - Bivee LLC"
  description: 
  keywords:

contact:
  phone: ''
  email: ''
  address: '201 Waterfront St, Fort Washington, MD 20745'

url:
permalink: /:title
  
social:

  
google:
  analytics : 'UA-43775034-1'
  domain: 'diversitywoman.com'

facebook:
  admins : ''
  api : ''

assets:
  img: '/assets/images/'
  css: '/assets/stylesheets/'
  js: '/assets/javascripts/'
  speaker: '/assets/images/speakers/'
  sponsor: '/assets/images/sponsors/'
  honoree: '/assets/images/honorees/'

eventbrite:
  event-id: '7020860583'
  app-key: '4HSDJIEFIFGXFYAM2Z'